In [1]:
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import KNNImputer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, f1_score, precision_score, recall_score

In [2]:
df_train = pd.read_csv("/content/train.csv", index_col= 0)

In [3]:
df_test = pd.read_csv("/content/test.csv", index_col= 0)

In [4]:
df_train.head()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,14dd8831-6af5-400b-83ec-68e61888a048,981165ec-3274-42f5-a3b4-d104041a9ca9,Fully Paid,445412.0,Short Term,709.0,1167493.0,8 years,Home Mortgage,Home Improvements,5214.74,17.2,NaN,6.0,1.0,228190.0,416746.0,1.0,0.0
1,4771cc26-131a-45db-b5aa-537ea4ba5342,2de017a3-2e01-49cb-a581-08169e83be29,Fully Paid,262328.0,Short Term,NaN,NaN,10+ years,Home Mortgage,Debt Consolidation,33295.98,21.1,8.0,35.0,0.0,229976.0,850784.0,0.0,0.0
2,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,5efb2b2b-bf11-4dfd-a572-3761a2694725,Fully Paid,99999999.0,Short Term,741.0,2231892.0,8 years,Own Home,Debt Consolidation,29200.53,14.9,29.0,18.0,1.0,297996.0,750090.0,0.0,0.0
3,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,e777faab-98ae-45af-9a86-7ce5b33b1011,Fully Paid,347666.0,Long Term,721.0,806949.0,3 years,Own Home,Debt Consolidation,8741.90,12.0,NaN,9.0,0.0,256329.0,386958.0,0.0,0.0
4,d4062e70-befa-4995-8643-a0de73938182,81536ad9-5ccf-4eb8-befb-47a4d608658e,Fully Paid,176220.0,Short Term,NaN,NaN,5 years,Rent,Debt Consolidation,20639.70,6.1,NaN,15.0,0.0,253460.0,427174.0,0.0,0.0

In [5]:
df_train.tail()

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
99995,3f94c18c-ba8f-45d0-8610-88a684a410a9,2da51983-cfef-4b8f-a733-5dfaf69e9281,Fully Paid,147070.0,Short Term,725.0,475437.0,7 years,Own Home,other,2202.86,22.3,NaN,5.0,0.0,47766.0,658548.0,0.0,0.0
99996,06eba04f-58fc-424a-b666-ed72aa008900,77f2252a-b7d1-4b07-a746-1202a8304290,Fully Paid,99999999.0,Short Term,732.0,1289416.0,1 year,Rent,Debt Consolidation,13109.05,9.4,21.0,22.0,0.0,153045.0,509234.0,0.0,0.0
99997,e1cb4050-eff5-4bdb-a1b0-aabd3f7eaac7,2ced5f10-bd60-4a11-9134-cadce4e7b0a3,Fully Paid,103136.0,Short Term,742.0,1150545.0,6 years,Rent,Debt Consolidation,7315.57,18.8,18.0,12.0,1.0,109554.0,537548.0,1.0,0.0
99998,81ab928b-d1a5-4523-9a3c-271ebb01b4fb,3e45ffda-99fd-4cfc-b8b8-446f4a505f36,Fully Paid,530332.0,Short Term,746.0,1717524.0,9 years,Rent,Debt Consolidation,9890.07,15.0,NaN,8.0,0.0,404225.0,738254.0,0.0,0.0
99999,c63916c6-6d46-47a9-949a-51d09af4414f,1b3014be-5c07-4d41-abe7-44573c375886,Fully Paid,99999999.0,Short Term,743.0,935180.0,NaN,Own Home,Debt Consolidation,9118.10,13.0,NaN,4.0,1.0,45600.0,91014.0,1.0,0.0

In [6]:
df_test.head()

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,f738779f-c726-40dc-92cf-689d73af533d,ded0b3c3-6bf4-4091-8726-47039f2c1b90,611314.0,Short Term,747.0,2074116.0,10+ years,Home Mortgage,Debt Consolidation,42000.83,21.8,NaN,9.0,0.0,621908.0,1058970.0,0.0,0.0
1,6dcc0947-164d-476c-a1de-3ae7283dde0a,1630e6e3-34e3-461a-8fda-09297d3140c8,266662.0,Short Term,734.0,1919190.0,10+ years,Home Mortgage,Debt Consolidation,36624.40,19.4,NaN,11.0,0.0,679573.0,904442.0,0.0,0.0
2,f7744d01-894b-49c3-8777-fc6431a2cff1,2c60938b-ad2b-4702-804d-eeca43949c52,153494.0,Short Term,709.0,871112.0,2 years,Rent,Debt Consolidation,8391.73,12.5,10.0,10.0,0.0,38532.0,388036.0,0.0,0.0
3,83721ffb-b99a-4a0f-aea5-ef472a138b41,12116614-2f3c-4d16-ad34-d92883718806,176242.0,Short Term,727.0,780083.0,10+ years,Rent,Debt Consolidation,16771.87,16.5,27.0,16.0,1.0,156940.0,531322.0,1.0,0.0
4,08f3789f-5714-4b10-929d-e1527ab5e5a3,39888105-fd5f-4023-860a-30a3e6f5ccb7,321992.0,Short Term,744.0,1761148.0,10+ years,Home Mortgage,Debt Consolidation,39478.77,26.0,44.0,14.0,0.0,359765.0,468072.0,0.0,0.0

In [7]:
df_test.tail()

,Loan ID,Customer ID,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
9995,c4ab66f9-833c-43b8-879c-4f8bcb64dd14,8ee2002b-8fb6-4af0-ab74-25a1c23e7647,157806.0,Short Term,731.0,1514376.0,6 years,Rent,Debt Consolidation,4795.41,12.5,NaN,9.0,0.0,87058.0,234410.0,0.0,0.0
9996,bbd3a392-01b4-4e0e-9c28-b2a4a39beac7,6c306306-f5c2-4db5-b74a-af2895123ecb,132550.0,Short Term,718.0,763192.0,4 years,Home Mortgage,Debt Consolidation,12401.87,9.9,20.0,8.0,0.0,74309.0,329692.0,0.0,0.0
9997,da9870de-4280-46a3-8fc6-91cfe5bfde9d,cc94e25e-1060-4465-b603-194e122f0239,223212.0,Long Term,NaN,NaN,NaN,Rent,Debt Consolidation,4354.42,27.2,NaN,8.0,1.0,99636.0,568370.0,1.0,0.0
9998,0cc8e0e0-1bc6-49d7-ad0f-0598b647458f,f90cf410-a34b-49e7-8af9-2b405e17b827,99999999.0,Short Term,721.0,972097.0,10+ years,Home Mortgage,Debt Consolidation,12232.20,16.8,24.0,8.0,1.0,184984.0,240658.0,0.0,0.0
9999,14f94b64-26c4-48fd-b916-1388d7adcc1d,f1838fa9-7ad9-44d5-97a6-7a6d3f3529d7,99999999.0,Short Term,748.0,1079960.0,6 years,Home Mortgage,Debt Consolidation,12239.61,19.7,NaN,14.0,0.0,179018.0,607882.0,0.0,0.0

In [8]:
df_train.shape

(100000, 19)

In [9]:
df_test.shape

(10000, 18)

In [10]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100000 entries, 0 to 99999
Data columns (total 19 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Loan ID                       100000 non-null  object
 1   Customer ID                   100000 non-null  object
 2   Loan Status                   100000 non-null  object
 3   Current Loan Amount           100000 non-null  float64
 4   Term                          100000 non-null  object
 5   Credit Score                  80846 non-null   float64
 6   Annual Income                 80846 non-null   float64
 7   Years in current job          95778 non-null   object
 8   Home Ownership                100000 non-null  object
 9   Purpose                       100000 non-null  object
 10  Monthly Debt                  100000 non-null  float64
 11  Years of Credit History       100000 non-null  float64
 12  Months since last delinquent  46859 non-null   float64
 13  Number of Open Accounts       100000 non-null  float64
 14  Number of Credit Problems     100000 non-null  float64
 15  Current Credit Balance        100000 non-null  float64
 16  Maximum Open Credit           99998 non-null   float64
 17  Bankruptcies                  99796 non-null   float64
 18  Tax Liens                     99990 non-null   float64
dtypes: float64(12), object(7)
memory usage: 15.3+ MB

In [11]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10000 entries, 0 to 9999
Data columns (total 18 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Loan ID                       10000 non-null  object
 1   Customer ID                   10000 non-null  object
 2   Current Loan Amount           10000 non-null  float64
 3   Term                          10000 non-null  object
 4   Credit Score                  8019 non-null   float64
 5   Annual Income                 8019 non-null   float64
 6   Years in current job          9573 non-null   object
 7   Home Ownership                10000 non-null  object
 8   Purpose                       10000 non-null  object
 9   Monthly Debt                  10000 non-null  float64
 10  Years of Credit History       10000 non-null  float64
 11  Months since last delinquent  4694 non-null   float64
 12  Number of Open Accounts       10000 non-null  float64
 13  Number of Credit Problems     10000 non-null  float64
 14  Current Credit Balance        10000 non-null  float64
 15  Maximum Open Credit           10000 non-null  float64
 16  Bankruptcies                  9978 non-null   float64
 17  Tax Liens                     9999 non-null   float64
dtypes: float64(12), object(6)
memory usage: 1.4+ MB

In [12]:
# df_train.drop("Loan ID", axis= 1, inplace= True)
# df_train.head()

In [13]:
# df_test.drop("Loan ID", axis= 1, inplace= True)
# df_test.head()

In [14]:
df_train.drop(["Loan ID", "Customer ID", "Years in current job"], axis= 1, inplace= True)

In [15]:
df_test.drop(["Loan ID", "Customer ID", "Years in current job"], axis= 1, inplace= True)

In [16]:
df_train.dtypes

Loan Status                      object
Current Loan Amount             float64
Term                             object
Credit Score                    float64
Annual Income                   float64
Home Ownership                   object
Purpose                          object
Monthly Debt                    float64
Years of Credit History         float64
Months since last delinquent    float64
Number of Open Accounts         float64
Number of Credit Problems       float64
Current Credit Balance          float64
Maximum Open Credit             float64
Bankruptcies                    float64
Tax Liens                       float64
dtype: object

In [17]:
df_test.dtypes

Current Loan Amount             float64
Term                             object
Credit Score                    float64
Annual Income                   float64
Home Ownership                   object
Purpose                          object
Monthly Debt                    float64
Years of Credit History         float64
Months since last delinquent    float64
Number of Open Accounts         float64
Number of Credit Problems       float64
Current Credit Balance          float64
Maximum Open Credit             float64
Bankruptcies                    float64
Tax Liens                       float64
dtype: object

In [18]:
df_train.describe().T

,count,mean,std,min,25%,50%,75%,max
Current Loan Amount,100000.0,1.176045e+07,3.178394e+07,10802.0,179652.0000,312246.0,5.249420e+05,1.000000e+08
Credit Score,80846.0,1.076456e+03,1.475404e+03,585.0,705.0000,724.0,7.410000e+02,7.510000e+03
Annual Income,80846.0,1.378277e+06,1.081360e+06,76627.0,848844.0000,1174162.0,1.650663e+06,1.655574e+08
Monthly Debt,100000.0,1.847241e+04,1.217499e+04,0.0,10214.1625,16220.3,2.401206e+04,4.358433e+05
Years of Credit History,100000.0,1.819914e+01,7.015324e+00,3.6,13.5000,16.9,2.170000e+01,7.050000e+01
Months since last delinquent,46859.0,3.490132e+01,2.199783e+01,0.0,16.0000,32.0,5.100000e+01,1.760000e+02
Number of Open Accounts,100000.0,1.112853e+01,5.009870e+00,0.0,8.0000,10.0,1.400000e+01,7.600000e+01
Number of Credit Problems,100000.0,1.683100e-01,4.827050e-01,0.0,0.0000,0.0,0.000000e+00,1.500000e+01
Current Credit Balance,100000.0,2.946374e+05,3.761709e+05,0.0,112670.0000,209817.0,3.679588e+05,3.287897e+07
Maximum Open Credit,99998.0,7.607984e+05,8.384503e+06,0.0,273438.0000,467874.0,7.829580e+05,1.539738e+09
Bankruptcies,99796.0,1.177402e-01,3.514238e-01,0.0,0.0000,0.0,0.000000e+00,7.000000e+00
Tax Liens,99990.0,2.931293e-02,2.581824e-01,0.0,0.0000,0.0,0.000000e+00,1.500000e+01

In [19]:
df_test.describe().T

,count,mean,std,min,25%,50%,75%,max
Current Loan Amount,10000.0,1.160380e+07,3.160010e+07,19470.0,178948.0000,309276.000,5.157075e+05,1.000000e+08
Credit Score,8019.0,1.077992e+03,1.477468e+03,585.0,706.0000,725.000,7.410000e+02,7.510000e+03
Annual Income,8019.0,1.369106e+06,8.687557e+05,81092.0,848340.5000,1168272.000,1.664390e+06,1.781535e+07
Monthly Debt,10000.0,1.842967e+04,1.239996e+04,0.0,10202.8575,16052.055,2.388134e+04,2.290579e+05
Years of Credit History,10000.0,1.823593e+01,7.018356e+00,3.8,13.6000,17.000,2.170000e+01,6.250000e+01
Months since last delinquent,4694.0,3.496464e+01,2.164029e+01,0.0,17.0000,32.000,5.000000e+01,1.310000e+02
Number of Open Accounts,10000.0,1.108410e+01,5.023380e+00,1.0,7.0000,10.000,1.400000e+01,5.500000e+01
Number of Credit Problems,10000.0,1.655000e-01,5.009340e-01,0.0,0.0000,0.000,0.000000e+00,1.000000e+01
Current Credit Balance,10000.0,2.907301e+05,3.881687e+05,0.0,108651.5000,207518.000,3.624630e+05,1.623744e+07
Maximum Open Credit,10000.0,6.871308e+05,1.861394e+06,0.0,270600.0000,462605.000,7.861150e+05,1.459073e+08
Bankruptcies,9978.0,1.163560e-01,3.499611e-01,0.0,0.0000,0.000,0.000000e+00,5.000000e+00
Tax Liens,9999.0,3.080308e-02,2.882150e-01,0.0,0.0000,0.000,0.000000e+00,9.000000e+00

In [20]:
df_train["Loan Status"].value_counts()

Fully Paid     77361
Charged Off    22639
Name: Loan Status, dtype: int64

In [21]:
type_dict = {"Fully Paid": 1,
             "Charged Off": 0}

df_train["Loan Status"] = df_train["Loan Status"].map(type_dict)
df_train["Loan Status"].value_counts()

1    77361
0    22639
Name: Loan Status, dtype: int64

In [22]:
print("Train : \n", df_train["Term"].value_counts())

print("==========================")

print("Test : \n", df_test["Term"].value_counts())

Train :
 Short Term    72208
Long Term     27792
Name: Term, dtype: int64
==========================
Test :
 Short Term    7295
Long Term     2705
Name: Term, dtype: int64

In [23]:
type_dict_Term = {"Short Term": 1,
                  "Long Term": 0,
                  "NaN": np.nan}

df_train["Term"] = df_train["Term"].map(type_dict_Term)
print("Train : \n", df_train["Term"].value_counts())

print("==========================")

df_test["Term"] = df_test["Term"].map(type_dict_Term)
print("Test : \n", df_test["Term"].value_counts())

Train :
 1.0    72208
0.0    27792
Name: Term, dtype: int64
==========================
Test :
 1.0    7295
0.0    2705
Name: Term, dtype: int64

In [24]:
print("Train : \n", df_train["Home Ownership"].value_counts())

print("==========================")

print("Test : \n", df_test["Home Ownership"].value_counts())

Train :
 Home Mortgage    48410
Rent             42194
Own Home          9182
HaveMortgage       214
Name: Home Ownership, dtype: int64
==========================
Test :
 Home Mortgage    4867
Rent             4203
Own Home          914
HaveMortgage       16
Name: Home Ownership, dtype: int64

In [25]:
type_dict_Home_Ownership = {"Home Mortgage": 1,
                            "Rent": 2,
                            "Own Home": 3,
                            "HaveMortgage": 4}

df_train["Home Ownership"] = df_train["Home Ownership"].map(type_dict_Home_Ownership)
print("Train : \n", df_train["Home Ownership"].value_counts())

print("==========================")

df_test["Home Ownership"] = df_test["Home Ownership"].map(type_dict_Home_Ownership)
print("Test : \n", df_test["Home Ownership"].value_counts())

Train :
 1    48410
2    42194
3     9182
4      214
Name: Home Ownership, dtype: int64
==========================
Test :
 1    4867
2    4203
3     914
4      16
Name: Home Ownership, dtype: int64

In [26]:
print("Train : \n", df_train["Purpose"].value_counts())

print("==========================")

print("Test : \n", df_test["Purpose"].value_counts())

Train :
 Debt Consolidation      78552
other                    6037
Home Improvements        5839
Other                    3250
Business Loan            1569
Buy a Car                1265
Medical Bills            1127
Buy House                 678
Take a Trip               573
major_purchase            352
small_business            283
moving                    150
wedding                   115
vacation                  101
Educational Expenses       99
renewable_energy           10
Name: Purpose, dtype: int64
==========================
Test :
 Debt Consolidation      7878
Home Improvements        593
other                    561
Other                    308
Business Loan            163
Buy a Car                142
Medical Bills            113
Buy House                 70
major_purchase            52
Take a Trip               44
small_business            31
Educational Expenses      14
moving                    14
wedding                   10
vacation                   6
renewable_energy           1
Name: Purpose, dtype: int64

In [27]:
type_dict_Purpose = {"Debt Consolidation": 1,
                     "Home Improvements": 2,
                     "Business Loan": 3,
                     "Buy a Car": 4,
                     "Medical Bills": 5,
                     "Buy House": 6,
                     "major_purchase": 7,
                     "Take a Trip": 8,
                     "small_business": 9,
                     "Educational Expenses": 10,
                     "moving": 11,
                     "wedding": 12,
                     "vacation": 13,
                     "renewable_energy": 14,
                     "other": 100,
                     "Other": 100}

df_train["Purpose"] = df_train["Purpose"].map(type_dict_Purpose)
print("Train : \n", df_train["Purpose"].value_counts())

print("==========================")

df_test["Purpose"] = df_test["Purpose"].map(type_dict_Purpose)
print("Test : \n", df_test["Purpose"].value_counts())

Train :
 1      78552
100     9287
2       5839
3       1569
4       1265
5       1127
6        678
8        573
7        352
9        283
11       150
12       115
13       101
10        99
14        10
Name: Purpose, dtype: int64
==========================
Test :
 1      7878
100     869
2       593
3       163
4       142
5       113
6        70
7        52
8        44
9        31
10       14
11       14
12       10
13        6
14        1
Name: Purpose, dtype: int64

In [28]:
imputer = KNNImputer(n_neighbors= 3)
df_train_clean = pd.DataFrame(imputer.fit_transform(df_train), columns = df_train.columns)
df_train_clean.isnull().sum()

Loan Status                     0
Current Loan Amount             0
Term                            0
Credit Score                    0
Annual Income                   0
Home Ownership                  0
Purpose                         0
Monthly Debt                    0
Years of Credit History         0
Months since last delinquent    0
Number of Open Accounts         0
Number of Credit Problems       0
Current Credit Balance          0
Maximum Open Credit             0
Bankruptcies                    0
Tax Liens                       0
dtype: int64

In [29]:
imputer = KNNImputer(n_neighbors= 3)
df_test_clean = pd.DataFrame(imputer.fit_transform(df_test), columns = df_test.columns)
df_test_clean.isnull().sum()

Current Loan Amount             0
Term                            0
Credit Score                    0
Annual Income                   0
Home Ownership                  0
Purpose                         0
Monthly Debt                    0
Years of Credit History         0
Months since last delinquent    0
Number of Open Accounts         0
Number of Credit Problems       0
Current Credit Balance          0
Maximum Open Credit             0
Bankruptcies                    0
Tax Liens                       0
dtype: int64

In [30]:
df_train_clean

,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,1.0,445412.0,1.0,709.000000,1.167493e+06,1.0,2.0,5214.74,17.2,22.333333,6.0,1.0,228190.0,416746.0,1.0,0.0
1,1.0,262328.0,1.0,746.000000,1.793245e+06,1.0,1.0,33295.98,21.1,8.000000,35.0,0.0,229976.0,850784.0,0.0,0.0
2,1.0,99999999.0,1.0,741.000000,2.231892e+06,3.0,1.0,29200.53,14.9,29.000000,18.0,1.0,297996.0,750090.0,0.0,0.0
3,1.0,347666.0,0.0,721.000000,8.069490e+05,3.0,1.0,8741.90,12.0,50.666667,9.0,0.0,256329.0,386958.0,0.0,0.0
4,1.0,176220.0,1.0,731.333333,1.183554e+06,2.0,1.0,20639.70,6.1,56.000000,15.0,0.0,253460.0,427174.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,1.0,147070.0,1.0,725.000000,4.754370e+05,3.0,100.0,2202.86,22.3,53.333333,5.0,0.0,47766.0,658548.0,0.0,0.0
99996,1.0,99999999.0,1.0,732.000000,1.289416e+06,2.0,1.0,13109.05,9.4,21.000000,22.0,0.0,153045.0,509234.0,0.0,0.0
99997,1.0,103136.0,1.0,742.000000,1.150545e+06,2.0,1.0,7315.57,18.8,18.000000,12.0,1.0,109554.0,537548.0,1.0,0.0
99998,1.0,530332.0,1.0,746.000000,1.717524e+06,2.0,1.0,9890.07,15.0,71.000000,8.0,0.0,404225.0,738254.0,0.0,0.0
99999,1.0,99999999.0,1.0,743.000000,9.351800e+05,3.0,1.0,9118.10,13.0,54.333333,4.0,1.0,45600.0,91014.0,1.0,0.0

In [31]:
X = df_train_clean.drop("Loan Status", axis= 1)
y_train = df_train["Loan Status"]

In [32]:
sc = StandardScaler()

In [33]:
X_test = df_test_clean

In [34]:
X_train = sc.fit_transform(X)
X_test = sc.transform(X_test)

In [35]:
rfc = RandomForestClassifier(criterion = "entropy", random_state = 75)

In [36]:
rfc.fit(X_train, y_train)

RandomForestClassifier(criterion='entropy', random_state=75)

In [38]:
y_pred_test = rfc.predict(X_test)
y_pred_train = rfc.predict(X_train)

In [37]:
scores = cross_val_score(rfc, X_train, y_train, cv= 10)
print("Mean cross-validation score: %.3f" % scores.mean())

Mean cross-validation score: 0.820